# Generated by Django 4.0.5 on 2022-07-09 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ManyToManyField(to='administration.producttrees')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.producttrees')),
            ],
        ),
    ]
