# Generated by Django 4.0.5 on 2022-07-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttrees',
            name='product',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
