# Generated by Django 4.0.5 on 2022-07-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_producttrees_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttrees',
            name='child',
            field=models.ManyToManyField(blank=True, null=True, to='administration.producttrees'),
        ),
        migrations.AlterField(
            model_name='producttrees',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.producttrees'),
        ),
        migrations.AlterField(
            model_name='producttrees',
            name='product',
            field=models.CharField(max_length=50),
        ),
    ]
