# Generated by Django 4.0.5 on 2022-07-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_producttrees_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttrees',
            name='child',
            field=models.ManyToManyField(blank=True, null=True, related_name='someName', to='administration.producttrees'),
        ),
    ]
