# Generated by Django 4.0.5 on 2022-07-11 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_alter_producttrees_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttrees',
            name='child',
        ),
        migrations.AddField(
            model_name='producttrees',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='administration.producttrees'),
        ),
    ]
