# Generated by Django 4.0.5 on 2022-07-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_remove_producttrees_child_producttrees_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttrees',
            name='child',
        ),
        migrations.AddField(
            model_name='producttrees',
            name='child',
            field=models.ManyToManyField(blank=True, null=True, related_name='children', to='administration.producttrees'),
        ),
    ]
