# Generated by Django 4.0.5 on 2022-07-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_remove_producttrees_child_producttrees_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttrees',
            old_name='child',
            new_name='parent',
        ),
    ]
