# Generated by Django 4.0.5 on 2022-07-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='contact_number',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
