# Generated by Django 4.0.5 on 2022-07-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_sellerprofile_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='contact_number',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
    ]
