# Generated by Django 4.0.5 on 2022-07-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_sellerprofile_is_phone_verified_sellerprofile_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='torque',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
