# Generated by Django 4.0.5 on 2022-07-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_sellerprofile_torque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='torque',
            field=models.IntegerField(blank=True, default=0, max_length=5, null=True),
        ),
    ]
