# Generated by Django 4.0.5 on 2022-07-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_sellerprofile_torque'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='shop_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
