# Generated by Django 4.0.5 on 2022-07-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_sellerprofile_resend_torque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
