# Generated by Django 4.0.5 on 2022-07-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_alter_sellerprofile_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_product', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
