# Generated by Django 4.0.5 on 2022-07-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_product_available_product_breadth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='upload_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
