# Generated by Django 4.0.5 on 2022-07-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorized', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='type',
            new_name='seller',
        ),
    ]
