# Generated by Django 4.0.5 on 2022-07-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorized', '0003_alter_usertype_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='verified_seller',
            field=models.BooleanField(default=False),
        ),
    ]
