# Generated by Django 4.0.5 on 2022-07-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorized', '0005_alter_usertype_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='seller',
        ),
        migrations.DeleteModel(
            name='SellerForm',
        ),
    ]
