# Generated by Django 4.0.5 on 2022-07-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorized', '0006_remove_usertype_seller_delete_sellerform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
